code: made huh better

diff --git a/huh b/huh
--- a/huh
+++ b/huh
@@ -1,11 +1,19 @@
 #!/bin/sh
-REPO=$1
-BUILD_FILE="$HOME/.huh/build/BUILD.box"
-
 log_error() {
   printf "\033[38;5;196m░▒▓\033[48;5;196;38;5;196m█\033[48;5;196;37;1m error: %s \033[48;5;196;38;5;196m█\033[0m\033[38;5;196m▓▒░\033[0m\n" "$1"
 }
 
+bonsai() {
+  printf "▙ %s\n\n" "$1"
+}
+
+[ -z "$1" ] && log_error "No repository specified." && exit 1
+REPO=$1
+BUILD_FILE="$HOME/.huh/build/BUILD.box"
+
+rm -rf ~/.huh/build
+
+bonsai "Downloading"
 git clone -q "https://github.com/$REPO" "$HOME/.huh/build/" > /dev/null 2>&1
 
 if [ ! -f "$BUILD_FILE" ]; then
@@ -16,18 +24,19 @@ fi
 
 cd "$HOME/.huh/build/" || exit 1
 
-while IFS= read -r line || [ -n "$line" ]; do
-  [ -z "$line" ] && continue
-  case "$line" in \#*) continue ;; esac
+bonsai "Running BUILD.box"
+mkdir PKGINSTALL
+. BUILD.box > /dev/null 2>&1
 
-  eval "$line"
-done < "$BUILD_FILE"
-
-if [ ! -d "./PKGINSTALL" ]; then
-  log_error "PKGINSTALL directory not found"
+bonsai "Installing package"
+if [ "$(echo ./PKGINSTALL/*)" != "./PKGINSTALL/*" ]; then
+  mv ./PKGINSTALL/* ~/.huh/
+else
+  log_error "PKGINSTALL is empty. Build script failed to output any files."
   rm -rf ~/.huh/build
   exit 1
 fi
 
-mv ./PKGINSTALL/* ~/.huh/
+bonsai "Cleaning up"
 rm -rf ~/.huh/build
+bonsai "done"
